In [1]:
from tensorflow.keras.preprocessing.sequence import pad_sequences


In [2]:
data=[[1,2,3,4],[5,6]]
padded=pad_sequences(data,padding='post')

In [3]:
padded

array([[1, 2, 3, 4],
       [5, 6, 0, 0]], dtype=int32)

In [6]:
data=[[1,2,3,4],[5,6]]
padded=pad_sequences(data,padding='post',maxlen=3)
padded

array([[2, 3, 4],
       [5, 6, 0]], dtype=int32)

In [7]:
# Masking rule:when we use padding when we tell to the model that zero / paddings values ignor it.

In [8]:
# Bucketing(Grouping): same length sequences throw the group(bucket),because this model use less padding  and training will be fast.

In [9]:
# truncating : if koi seq. bahut jyda bda hai to usko cut kar do / sirf recentpart rkho ( ex. last 100 steps)

In [10]:
# varying size data= input ki alag alg lenth size

In [15]:
# string padding
text = "hello"
print(text.ljust(10, '-'))  # Output: 'hello-----'


hello-----


In [17]:
text="rahul"
print(text.rjust(15,"0"))

0000000000rahul


In [20]:
text = "hello"
print(text.center(11, '='))  # Output: '===hello==='


===hello===


In [21]:
# number padding

In [22]:
num = "42"
print(num.zfill(5))  # Output: '00042'


00042


In [23]:
num = 7
print("{:04}".format(num))  # Output: '0007'
print(f"{num:04}")          # Output: '0007'


0007
0007


In [25]:
x="20"
print(x.zfill(5))

00020


In [26]:
num=52
print("{:04}".format(num))

0052


In [31]:
print(f"{num:05}")

00052


In [32]:
# list padding

In [33]:
lst = [1, 2]
target_length = 5
padded = lst + [0] * (target_length - len(lst))
print(padded)  # Output: [1, 2, 0, 0, 0]


[1, 2, 0, 0, 0]


In [34]:
list=[2,4]
target_length=5
padded=list+[0]*(target_length - len(list))
print(padded)

[2, 4, 0, 0, 0]


In [35]:
x=[5,6,9]
t=10
p=x+[0]*(t-len(x))
print(p)

[5, 6, 9, 0, 0, 0, 0, 0, 0, 0]


In [36]:
# padding in Numpy

In [41]:
import numpy as np
arr = np.array([1, 2, 3])
padded = np.pad(arr, ( 2,3), constant_values=0)
print(padded)  # Output: [0 0 1 2 3 0 0 0]


[0 0 1 2 3 0 0 0]


In [48]:
arr=np.array([2,6,5,56,23])
padded=np.pad(arr,(2,3),constant_values=0)
print(padded)

[ 0  0  2  6  5 56 23  0  0  0]


In [50]:
# padding in deep learning
from tensorflow.keras.preprocessing.sequence import pad_sequences

sequences = [[1, 2], [3, 4, 5]]
padded_seq = pad_sequences(sequences, padding='post')
print(padded_seq)



[[1 2 0]
 [3 4 5]]
